### PR TITLE
Issue 316

### PR DESCRIPTION
**Pull request by nikolai-b**
This will remove subscribers names if they have selected in their user prefs so an extension to #316

This will add a few more db queries so might slow some pages a bit.

### CODE REVIEW

**Comment by nikolai-b** [comment]
ha, no, sorry.  Have fixed.  I think this covers all cases.  I haven't added "and 3 other users" to thread subscribers as I thought that it isn't high priority but can do if you like.

**Comment by mvl22** [comment]
Thanks. As a main first iteration, removing the names is great. Naturally, replacing all the "Anon"s with a single box "and 3 other users" will be an improvement in future as it shortens the page.

**Comment by nikolai-b** [comment]
So that isn't quite what I've done here.  For the list of subscribers to a thread, users with private profiles will simply not appear at all (unless the view shares a group with them).  The replacing with 'Anon' only happens if a user with a private profile was the last to edit or created a note, thread, or issue.  E.g. before Issue Reported by Lou on 09-02-2015 will now be Reported by Anon on 09-02-2015.

**Comment by nikolai-b** [comment]
Looking at all the issues around this I'd like to clarify what is wanted regarding privacy. 

From #316 and talking to @mvl22 I thought that if users had selected to have their profiles private then only users who share a group with them can see their profile link (otherwise it is replaced with anon) - this is solved by this pull. But looking at #314 it looks like there is a discussion about showing display name instead of real name.

For what it is worth showing different names depending on if you share a group or not seems pretty confusing.

**Comment by gravitystorm** [comment]
The detection of whether the user has permission to view the profiles is better done using the decl_auth framework. For example, `has_permission_on :user_profiles, to: :view` at https://github.com/cyclestreets/cyclescape/blob/master/config/authorization_rules.rb#L104 can be restricted as required - existing examples of fine-grained control are elsewhere in the same file. Since there's already lots of has_permission_to?(:view, ...) elsewhere in the code it makes sense to do the same here.

**Comment by nikolai-b** [comment]
Thanks @gravitystorm using the framework made sense.  I decided to go for permissions on the user instead of on the user_profile as this made more sense for the views.  The specs pass.

**Comment by nikolai-b** [comment]
The last change here will allow members with groups that overlap to see a person's real / full name.  This seems like a privacy change (but a relatively minor one) that would require an email to all users.  Probably a good time for #313 to be done.  If we are not ready for this then I can merge all the other commits and leave the last one.

**Comment by gravitystorm** [comment]
Code looks good. I'd suggest (similarly to #347 )

* make the PR against `staging` rather than `master`

**Pull request closed without merging**
