### PR TITLE
Remove jquery tools

### PR DESCRIPTION
**Pull request by nikolai-b**
This removes jQuery Tools.  It will require some testing and probably some tweaking.  If I merge it into staging do you have time to check some of the overlay, datepicker stuff @mvl22 ?

### CODE REVIEW

**Comment by mvl22** [comment]
Yes, there are quite a few problems:

1. New thread overlay looks different without the grayed background behind it and the close button (showing in the top-left) isn't shown properly:



2. Library section isn't scrollable:



3. Date picker appears semi-transparent:



4. My Cyclescape page isn't hiding the tab content properly - they are shown all auto-expanded, with the tabs becoming links to lower down on the page:



5. The auto-scroll didn't work for me I think. (I might need to check this again.)

**Comment by nikolai-b** [comment]
In b7013b8 I've dealt with 1) Overlay and 3) Datepicker transparency.  I've made a start on 2) Library section but it will need more work.

**Comment by nikolai-b** [comment]
@mvl22 I have address these issues, can you take a look?

**Comment by mvl22** [comment]
The overview page seems to have turned into having the Verdana font, I think.

**Comment by nikolai-b** [comment]
Thanks, on my system it was showing at as the same font (I don't have Verdana installed...)  Fixed in d939f627c6725d00275dec0ae3d6c4071870ce52 if that is the last issue we can remove jQuery Tools, which is great news!

**Comment by mvl22** [comment]
Thanks - definitely better. Two problems remaining:

1) Map type switching looks wrong:

map

2) Date picker does not have next/previous month control visible, and lacks padding on the right edge:

datepicker

**Comment by mvl22** [comment]
Thanks - the route drawing stuff seems fixed.

I'm still not seeing the next/previous month arrows in the date picker, and the right edge of the date picker box is still lacking padding.

If you could fix those up, assuming you're happy, do merge into master and I'll push this all live.

**Comment by nikolai-b** [comment]
Hmm, I'm seeing the next / previous buttons.  If I merge to master can we re-enable automatic deploys to the staging site?  It would help test as that does something seems to do something slightly different with assets (and I can't easily test sub domains locally).

**Comment by mvl22** [comment]
I'm a bit wary of generally treating cyclescape5 as a test-bed - it's really intended as something we can switch over to if something goes wrong on the main server.

However, I think this particular case is pretty low risk as we're not doing database migrations, etc.

If you can merge into master, I'll roll it out and enable automatic deploys for a while.

**Comment by nikolai-b** [comment]
Yes agreed.  Staging is the testbed and I'm only happy to merge to master when we are happy.

**Comment by mvl22** [comment]
Now rolled out on cyclescape3 and cyclescape5.

The auto-scroll doesn't seem to be working unfortunately. There are a couple of JS errors appearing in the browser's JS console.

**Comment by mvl22** [comment]
Thanks. I see 4c11efd56c3a9ba6fcc80ed76bf4073fb219e8b0 seems to fix the auto-scroll - thanks.

Rolled out to cyclescape3.

**Comment by mvl22** [comment]
I've spotted that the Street View reply type doesn't actually load the Street View image.

**Comment by nikolai-b** [comment]
Thanks, that one is hard to spot because turbo-links caches stuff so it depends on where you last did a page refresh.  I *think* it is fixed now.

**Comment by mvl22** [comment]
Yep, fine now. Rolled out.

**Comment by mvl22** [comment]
There is still the problem with the date picker that the arrows to go the previous/next month are not visible. They should be in the top-left and top-right corner of this box:

Picture

**Comment by nikolai-b** [comment]
Hi, sorry about this.  It is an asset issue, I've tried fixing it https://github.com/cyclestreets/cyclescape/commit/4d010ec9cf9d627c083e730e83a63304bcdb9040 but if that doesn't work I'll move the assets over from the `vendor` folder.

**Comment by mvl22** [comment]
Another snag just found - the edit cog symbol on an issue or all the way down the thread pages is not doing anything - should give a hover menu.

**Comment by nikolai-b** [comment]
I think this might have been to do with OpenLayers (I was getting an error in the JS console).  The menu is working for me locally though.  I've bumped OpenLayers in staging but it is not ready (on new issues it doesn't pick up the drawn location).  Are you getting any js errors from `getComputedStyle`?  If not I'll revert the OpenLayers update and see if the other change in staging fixes it for you.

**Pull request merged**
