### PR TITLE
Profile link master

### PR DESCRIPTION
**Pull request by nikolai-b**
The profile link #370 from commits cherry picked into a branch against master.

### CODE REVIEW

**Comment by mvl22** [comment]
Please do merge in when you're happy.

**Comment by nikolai-b** [comment]
This has been in master for a week now but hasn't been deployed, is the deploy still on manual or do we have a problem?

**Comment by mvl22** [comment]
Yes, I'm afraid there is a problem - on the local machine I tried the cherry-picked code didn't actually run all the settings pages. I'll check again and report here. Keen to get it live.

**Comment by mvl22** [comment]
I'm afraid I've found the following problems, running against master, on my local machine:

1) [Actually OK now] On /settings/edit, if I press submit, this takes me to /users/<id>-<moniker>/profile, with "We're sorry, but something went wrong.". Going to that same URL as a fresh GET request works fine. Looking at the Rails error log, I can see it was complaining about a missing asset in the Dragonfly area, which... I recall my localhost doesn't actually have. So seems the missing file was causing the whole page to 500, whereas a simple GET doesn't. Anyway, I've uploaded a file and that's caused the Dragonfly area to be created, and it's all working fine now.

2) /settings/preferences just gives "We're sorry, but something went wrong." on a simple GET request. The production log says:

```
ActionView::Template::Error (undefined method `profile_visibility' for #<UserPref:0x00000005f2f418>):
    17:       = f.input :enable_email
    18:       %h2= t ".profile"
    19:       %p= t ".profile_guidance_html", profile_link: link_to(t(".your_profile"), current_user_profile_path)
    20:       = f.input :profile_visibility,
    21:           as: :radio,
    22:           collection: UserPref::PROFILE_OPTIONS.map {|n| [t(".profile_#{n}"), n] }
    23:     = f.actions
  app/views/user/prefs/edit.html.haml:20:in `block (2 levels) in _app_views_user_prefs_edit_html_haml__83808095131858328_52754840'
  app/views/user/prefs/edit.html.haml:6:in `block in _app_views_user_prefs_edit_html_haml__83808095131858328_52754840'
  app/views/user/prefs/edit.html.haml:5:in `_app_views_user_prefs_edit_html_haml__83808095131858328_52754840'
```

**Comment by nikolai-b** [comment]
1. Just to check, nothing for me to do with that right?
1. That is only a problem on your local machine (as you have run the migration removing `profile_viability` from `UserPref`).  If you can do `rake db:schema:load` which will wipe your local database or use a copy of the production db it then it works fine.
1. Ah, great, thanks.  Fixed in e183141 (same with `locations`, it should definitely have the missing 's')

**Comment by mvl22** [comment]
Sorry but on overview#planning-applications and /overview#issues-nearby the no locations link is still set to /user/locations whereas the /user/locations page itself has a button to /settings/locations which is the correct one.

This is not a blocker, so have rolled out on cyclescape5 then live to cyclescape3.

If you could fix this up at some point soon, to ensure consistency, and add the privacy policy page I can then publish the blog post about the changes.

**Comment by nikolai-b** [comment]
Sorry I fixed all the internal routing but for some reason excluded that haml file in my grep.  Fixed now.

>  add the privacy policy page

Could you point me to where this is?  I must have missed it.

**Comment by mvl22** [comment]
> Could you point me to where this is? I must have missed it.

I e-mailed it - hopefully it got through OK.

**Pull request merged**
