### PR TITLE
Fixing layout glitch in thread display

### PR DESCRIPTION
**Pull request by DoccyB**
Fixed "Please sign in to vote" overlap

### CODE REVIEW

**Comment by nikolai-b** [comment]
Ah, great spot again.  I never adjusted this when I added the :+1: .

The reduction to 40px isn't enough though:

screenshot from 2018-05-03 20-55-42

You can see that the "Please sign in to vote" is still too high.  Reducing it to 10px looks better:

screenshot from 2018-05-03 20-56-00

Mind updating this PR to that and I'll merge?

**Comment by DoccyB** [comment]
Likewise, looking at the "issues" tab

Before:
screen shot 2018-05-03 at 22 44 46

And after, with 40px:
screen shot 2018-05-03 at 22 45 44

Thoughts on why our views differ?

**Comment by nikolai-b** [comment]
Oh dear, this is likely to be systematic to a much bigger issue.  I'm on Chromium 66.0.3359.117.  Now I've just checked and on Firefox I'm seeing this also.  Rubbish.  Thanks very much for raising this.

**Comment by nikolai-b** [comment]
Seems like Firefox defaults to some pretty bad Helvetica default.

https://github.com/cyclestreets/cyclescape/commit/d2ca7744419031d8bc62e81fe72eab45254867b8

I think that fixes things for me, are you able to test locally (note I still had to reduce the font on FF to 10px ).

Thanks

**Comment by mvl22** [comment]
Well spotted - thanks!

@DoccyB Thanks for the contribution :)

**Comment by nikolai-b** [comment]
@mvl22 I've tested the new CSS changes on Chrome and FF on linux.  Last time I tried this I got the CSS wrong #772.  Mind testing these changes?  I've pushed to staging.

Also thanks @DoccyB, it'd be great if you could also let me know if this looks ok locally for you.

**Pull request merged**
