### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by nikolai-b**
@mvl22 if your happy then I've added the cyclestreets photo map as a reply type and added the membership link.  I'd like to deploy this but we'd be good to check you are happy.

### CODE REVIEW

**Comment by nikolai-b** [comment]
I've added the option of threads to have leaders, have I done this as you intended?

**Comment by mvl22** [comment]
@nikolai-b Just back from holiday now, so planning to work through the backlog including looking at staging for the various changes - hopefully tomorrow.

**Comment by nikolai-b** [comment]
@mvl22 great, let me know can I'll get it out when your happy.

**Comment by mvl22** [comment]
NB My review comment just above refers to the two-level menu stuff.
(Not sure that GitHub has quite thought this UI change through - it's not at all clear!)

**Comment by nikolai-b** [comment]
I believe all the issue's you've raised have been addressed.  If not please comment here and I'll get them fixed.  This has become quite a large release.

**Comment by nikolai-b** [comment]
@mvl22 let me know when you've had a chance to look over it please.

**Comment by nikolai-b** [comment]
@mvl22 have you had a chance to look at this yet?

**Comment by mvl22** [comment]
All good to deploy to live - thanks.

There are small some tidy-ups I'll propose, but let's get this live first.

**Comment by nikolai-b** [comment]
Great,  I've got some time this evening so I'll do it then.  If you can make a list of some of the tidy-ups I can get started on them also.  Thanks for checking it.

**Comment by mvl22** [comment]
Could we get the What's new updated?

**Comment by nikolai-b** [comment]
Yes, sorry done now.

**Pull request merged**
