### PR TITLE
[WIP] Next release

### PR DESCRIPTION
**Pull request by nikolai-b**
There are a few more changes but along with a [Ruby and passenger](https://github.com/cyclestreets/cyclescape-chef/compare/c2a7546847cffc4fa8b10dc8b45eb1d0d0d0be08...45ca91498005094f633b555affca28abf3612ab4) upgrade this is what is in the next release.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
Czech translation is complete now on Transifex, so please include it.

**Comment by nikolai-b** [comment]
Done, thanks.

**Comment by mvl22** [comment]
I'm not really going to have the energy to check this over, but please do make it live as soon as you're happy. As far as I can see it's a mix of deployment stuff (which I presume you'd be monitoring), translation changes (which are low risk) and API changes (ditto).

Thanks both for all these efforts!

**Comment by mvl22** [comment]
As always, please do update the What's new page.

**Comment by nikolai-b** [comment]
Ah yes.  Will do.

**Pull request merged**
