### PR TITLE
Performance deploy

### PR DESCRIPTION
**Pull request by nikolai-b**
@mvl22 see #857 for the background and places to that there might be issues

### CODE REVIEW

**Comment by nikolai-b** [comment]
@mvl22 this could be tested on the new staging if you update your hosts file.

**Comment by mvl22** [comment]
All seems to be working fine - good to get this infrastructure stuff in place.

**Comment by mvl22** [comment]
Wow, this is so much faster. Well done.

Do keep an eye on the rollbar notifications - I see there's been a couple.

**Comment by nikolai-b** [comment]
Great, very pleased the performance is much better.

The errors were me.  Looks like the admin site_config view page is broken.  I wanted to check our new staging worked with images.  It does!

When you're ready can we get a new machine for cyclescape.org, I'll set it up and we can give it a test run but basically it should look like the new staging.

**Comment by mvl22** [comment]
> When you're ready can we get a new machine for cyclescape.org, I'll set it up and we can give it a test run but basically it should look like the new staging.

Yep, am about to sort this out.

**Pull request merged**
