### PR TITLE
Use "following" consistently

### LINKED ISSUE #258: Unsubscribe from followed threads using web-interface may not be clear
I couldn't work out how to unsubscribe from a thread I was following on cyclescape for long enough to create a git-hub account to report it.

Edit:  Just found the greyed out button.  I was trying to click the green tick.  I also tried changing the thread priority to 'Not interested'

Tags: usability

### PR DESCRIPTION
**Pull request by nikolai-b**
Stop using "subscribe"
Fixes #258

### CODE REVIEW

**Comment by nikolai-b** [comment]
@mvl22 as I'm changing the text would you mind checking / approving?  Thanks

**Comment by nikolai-b** [comment]
@mvl22 is this text change ok?

**Comment by mvl22** [comment]
I'm in favour of consistency, but to me "subscribed to" makes much more sense than "following", which has always felt like an odd description.

**Comment by nikolai-b** [comment]
Fine with me, I guess I'll change all mentions of 
unfollow -> unsubscribe
and 
follow -> subscribe

**Pull request merged**
