### PR TITLE
Rails4

### PR DESCRIPTION
**Pull request by nikolai-b**
This is not ready to merge (wip).

### CODE REVIEW

**Comment by nikolai-b** [comment]
@mvl22 so when you have time this is good to be checked.  It is a pretty massive upgrade so I expect some things will be a bit broken but all the specs pass.

**Comment by mvl22** [comment]
Presumably we must get all the privacy changes (which are blocked on me getting the privacy policy to you - will e-mail this to you now) live first?

**Comment by mvl22** [comment]
As soon as the privacy change is live (see e-mail just sent to you), which should clear all outstanding other code, I'll download this Rails4 branch and test - there are obviously migrations which won't then enable me to test out other branches still on older rails.

**Comment by mvl22** [comment]
I've done a fresh VM install (my old one was running out of space!), rolled out master and copied in the latest database dump (but not the image/document assets, to save space); that does work. I've then re-run chef but looking at the ```rails4``` branch instead.

On http://localhost:8080/overview I get an error 500, with the following production.log error:

```
  CACHE (0.0ms)  SELECT COUNT(*) FROM "user_locations" WHERE "user_locations"."user_id" = $1  [["user_id", 5]]
  Rendered planning_applications/_tinymap.html.haml (1.4ms)
  Rendered planning_applications/_planning_application.html.haml (2.5ms)
  Rendered dashboards/show.html.haml within layouts/application (1547.2ms)
Completed 500 Internal Server Error in 1631ms

ActionView::Template::Error (No route matches {:action=>"geometry", :controller=>"planning_applications", :format=>:json, :id=>nil} missing required keys: [:id]):
    1: - m = tiny_display_map(planning_application, geometry_planning_application_path(planning_application, :json), "tinymap") do |map, page, dom_id|
    2:   %div{id: dom_id, class: "tinymap", style: "#{planning_application.part_hidden? ? 'height: 100px' : ''}"}
    3: != m.to_html
  app/views/planning_applications/_tinymap.html.haml:1:in `_app_views_planning_applications__tinymap_html_haml__2683722575514727102_79329640'
  app/decorators/planning_application_decorator.rb:16:in `tinymap'
  app/views/planning_applications/_planning_application.html.haml:4:in `_app_views_planning_applications__planning_application_html_haml___1845611445969346950_79547920'
  app/views/dashboards/show.html.haml:135:in `_app_views_dashboards_show_html_haml__3584020529383025361_76316240'
```

**Comment by mvl22** [comment]
Apart from that I can't find any other problems - well done!

**Comment by nikolai-b** [comment]
@mvl22 so I've fixed the planning application issue (on the overview page) BUT I've also introduced a route change: `settings/accounts` which is now `settings/edit`.  I know this is annoying as we have just publicised the other route but the code is much cleaner (and I think it will fix https://github.com/cyclestreets/cyclescape/pull/383#issuecomment-113433754).  Let me know what you think.

**Comment by mvl22** [comment]
I saw the first commit earlier tonight ended up with a routes conflict (two current_user_profile routes I think it was), but I see that seems to have been resolved in the other commit.

Change of URL is acceptable - thanks for flagging it up though.

All seems good - please do merge into master!

**Comment by nikolai-b** [comment]
Ok, as this is a big change I'd like to make sure I'm around (just in case).  How about Mon evening we go live with this @mvl22 ?

**Comment by mvl22** [comment]
Sure, sounds good.

**Comment by nikolai-b** [comment]
@mvl22 ready when you are

**Comment by mvl22** [comment]
Thanks; rolling out on cyclescape5 now, then cyclescape3 if all OK.

**Comment by mvl22** [comment]
All rolled out live, so please do delete this branch. Thanks!

On to Rails 4.2 now?

**Comment by nikolai-b** [comment]
yep, seems like a good step.  First I need to set `config.secret_key_base`.

**Pull request merged**
