### PR TITLE
Allow two word tags

### LINKED ISSUE #574: Two-word tags are encouraged but not supported
AFAIK this issue has always existed, and it's now more relevant as tags can be used with @georgio8's issues map.

If you enter a `two word` tag, ie containing a space, then the input screen considers it a single tag, eg:
image

However, once the issue is created it becomes two separate tags:
image

(I'm sure I've seen a guide specifically encouraging `two word` tags but typically I can't find it now).

### PR DESCRIPTION
**Pull request by nikolai-b**
Split only on commas (as the js tagging lib does)
Convert spaces to - which keeps consistency
Fixes #574

@mvl22 thoughts?

### CODE REVIEW

**Comment by nikolai-b** [comment]
@mvl22 any objections to me merging this in? 
Currently if someone adds tags:
"bike parking" 
this is converted to "bike" and "parking".
This change will mean it is converted to "bike-parking".

**Comment by mvl22** [comment]
I've not been sure either way, but happy that we give this a go.

However, I can't see anything in the page template that gives clarity to the user as to what they can enter, i.e. that they are supposed to put commas to separate.

**Comment by nikolai-b** [comment]
I'm not sure that is required.  I think the templates have suggested this was comma separated already from the help text and from how the tagging library displays commas and spaces:

screenshot from 2016-07-22 09-26-20

Do you think this requires more clarity?

**Comment by nikolai-b** [comment]
Add 
> comma seperated list of tags
to the help text.

**Pull request merged**
