### PR TITLE
Expose message email address

### PR DESCRIPTION
**Pull request by nikolai-b**
Not to be merged yet!

### CODE REVIEW

**Comment by nikolai-b** [comment]
@mvl22 did you say you didn't want this (it adds an email link to messages)

**Comment by mvl22** [comment]
Presumably this is to address #44? (Would be useful if there is always a reference to an issue number somewhere please.)

I've added more detail to that ticket. There needs to be some labelling, and in particular, the e-mail address must only be shown to logged-in users.

**Comment by nikolai-b** [comment]
Merging, I've shorten the text to "Reply by email"
https://github.com/cyclestreets/cyclescape/commit/ece403aeb86dbf8e3245a37ddf271ca097a32209#diff-63ce76535a96f7acb5e8e66cea31936bR860
I can make it longer if your prefer.  If your happy I'll merge into staging to test.

**Comment by mvl22** [comment]
> Reply by email

That's fine.

**Pull request merged**
