### PR TITLE
Release

### PR DESCRIPTION
**Pull request by nikolai-b**
This adds
* multiple locations #309
* group hide #662 
* tag api #670 
* user search in admin #669

Let me know when your happy @mvl22 and I'll deploy

### CODE REVIEW

**Comment by nikolai-b** [comment]
Oh, and adds a a potential members email list #50 - the explanatory text will need re-wording as I do not believe I have made it very clear, sorry.

**Comment by nikolai-b** [comment]
@mvl22 bump

**Comment by nikolai-b** [comment]
@mvl22 I believe I've address all the issues you've raised.  Let me know if your happy for this to go live.

**Comment by mvl22** [comment]
All ready to go live, but if you can fix making the blue darker (#309) in doing so, that would be great.

**Pull request merged**
