### PR TITLE
Changed deadline date format to include day in word format.

### PR DESCRIPTION
**Pull request by nikolai-b**

### CODE REVIEW

**Comment by nikolai-b** [comment]
@rbazinet again two falling specs:

`rspec ./spec/features/dashboards_spec.rb:154 ./spec/features/messages/deadline_messages_spec.rb:15`

I know they are minor and it looks like the change you've made but would you mind updating them please?

**Comment by rbazinet** [comment]
Same here, I'll take a look tomorrow.

--Rob Bazinet
Founder ofStill River Software Company, LLC(http://stillriversoftware.com)
(o)(860) 263-0396(tel:(860)%20263-0396)
(m)(860) 942-9291(tel:(860)%20942-9291)

**Comment by rbazinet** [comment]
Fixed. I have some specs that continually fail and I think I thought these specs were those. If that makes sense.

-- 
Rob Bazinet
Founder of  Still River Software Company, LLC
(o) (860) 263-0396
(m) (860) 942-9291

Blog - Accidentaltechnologist.com  
Ruby & Mobile Community Editor - http://www.infoq.com  
LinkedIn Profile - http://www.linkedin.com/in/rbazinet


From: Rob Bazinet <rbazinet@stillriversoftware.com>
Reply: Rob Bazinet <rbazinet@stillriversoftware.com>
Date: January 24, 2016 at 4:34:07 PM
To: cyclestreets/cyclescape <cyclescape@noreply.github.com>, cyclestreets/cyclescape <reply@reply.github.com>
Subject:  Re: [cyclescape] Changed deadline date format to include day in word format. (#498)  

Same here, I'll take a look tomorrow.

--
Rob Bazinet
Founder of  Still River Software Company, LLC
(o) (860) 263-0396
(m) (860) 942-9291

On Jan 24, 2016, 3:34 PM -0500, Nikolai <notifications@github.com>, wrote:
@rbazinet again two falling specs:

rspec ./spec/features/dashboards_spec.rb:154 ./spec/features/messages/deadline_messages_spec.rb:15

I know they are minor and it looks like the change you've made but would you mind updating them please?

**Comment by nikolai-b** [comment]
Yes, makes sense.  If you notice some very bad ones please point them out, it won't be top priority but I'd like to remove some of the worst offenders.

**Pull request merged**
