### PR TITLE
Add basic issues API controller

### PR DESCRIPTION
**Pull request by nikolai-b**
I will be working on the LCC API here, not ready to merge yet.

### CODE REVIEW

**Comment by nikolai-b** [comment]
So this is nearly done.
A few things:

* The planit API doesn't give a deadline date so I can't automatically pull it in (it gives when the app was submitted but not the deadline).
* The spec doc wanted the group of the issue, that isn't possible as issues are created by a user and don't really belong to a group.
* The spec wanted a name, if the user's profile is public or they have a display name that is shown, otherwise its anon.
* There is no summary, if LCC want a shortened version of the description then they can trim it but I don't want to add a summary field unless you think we really should.
* If an issue doesn't have a deadline then I'm defaulting to the `created_at` date for `start_date` and `end_date` filtering.
* The results are paginated using `page` and `per_page` (default 200, max 500)

**Comment by mvl22** [comment]
Great work. One thing that has occurred to me is whether the default API output for issues ought to be GeoJSON rather than flat JSON - as that means that there is little work to put it straight on a map, and it's almost as simple to show listings.

I'd need to agree that with George but would that cause any difficulties?

Hmm... actually isn't that basically what is already present at
/issues/all_geometries.json
as used for the map view at: http://www.cyclescape.org/issues ?

I'll ask upstream about the deadlines for planning applications - that would be useful generally anyway.

In terms of the summary field, can this be added automatically, to avoid a client having to write a truncation algorithm?

**Comment by mvl22** [comment]
Does Rails make it easy to provide automatic documentation?

I'm thinking of a page at /api .

**Comment by nikolai-b** [comment]
I've moved to [grape](https://github.com/ruby-grape/grape) which is self documenting (it will respond with sensible errors).  I've also added an generated markdown https://github.com/cyclestreets/cyclescape/blob/lcc_api/grape_doc/API.md an you can point the developers to that.

**Comment by mvl22** [comment]
Thanks - will try shortly.

NB typo: GoeJSON

**Comment by nikolai-b** [comment]
Are you happy with this @mvl22, can it go live for LCC to try out.

**Comment by mvl22** [comment]
@nikolai-b Sorry - had a busy week; will confirm shortly.

**Comment by mvl22** [comment]
Good to go, though I'd prefer that the placeholder hint for the URL column did have http:// at the start, to make clear that people can paste in a full web address. If you could adjust this before merging to master that would be good.

**Comment by mvl22** [comment]
Thanks; all rolled out and looking good.

**Comment by mvl22** [comment]
Where is the documentation now? It seems to have disappeared.

**Pull request merged**
