### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by nikolai-b**
At the risk of having too many PRs open, I'm happy with this code going into master.  Do we have a process for this?

### CODE REVIEW

**Comment by gravitystorm** [comment]
There's no real process, but the way it works is on a "you break it, you get to keep it" approach! So when I used to do the merging, I would do so towards the end of the day (so that it included as much stuff as was in staging as possible) but with plenty of time left so that I could fix things if the deployment went wrong.

My approach was always to
* locally, run the tests on staging. This finds anything that's amiss after PR merging etc
* locally, merge staging into master, and deal with any merge conflicts
* locally, update the public changelog (app/views/pages/changelog.html.haml) by going through the git log
* locally, run the tests again, just to be double-sure
* push master to the repo
* check around 15-20 minutes past the hour that everything is still working, and that the new version is live
* `git checkout staging && git merge master --ff-only` to make sure I left my local repo ready for more work

I'd suggest avoiding using PRs for merging into master, since the automatic merging check doesn't ensure that the tests also pass.

Apart from that, feel free to deploy!

**Comment by mvl22** [comment]
Just to say that I've temporarily disabled automatic deployment of master.

**Comment by nikolai-b** [comment]
@mvl22 I've merged this in.  When your ready to enable automatic deployment let me know.  These changes are mainly upgrading testing libraries so I'm not worried about safety.

**Comment by mvl22** [comment]
@nikolai-b Update done. Are the other things ready to start to push through to master?

btw: You can always check the latest status of the site by looking at the revision ID in the footer of the page.

**Pull request merged**
