### PR TITLE
update Czech locale

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by nikolai-b** [comment]
Thanks for the PR!

Is this from Transfex? As in if I do 
```bash
bundle exec rake transifex:pull 
```
then the changes (other than the translation of Threads) is this change in there?

**Comment by PetrDlouhy** [comment]
@nikolai-b No, I changed this directly in the locales. I think, that the Transifex locale is outdated and I also added few translation that are not in the English locale (are left default as the variable name).

**Comment by nikolai-b** [comment]
Ok, I think the system is to update Transifex, if it is outdated then we can push the translations 
https://github.com/cyclestreets/cyclescape/blob/staging/TRANSLATE.md#developers.  I thought that is what we agreed in
https://github.com/cyclestreets/cyclescape/pull/547#issuecomment-226730056

I've just pushed the latest translations and can pull the updates but I don't want to clash with this PR until we are all happy.  If Transifex doesn't work well for you we could look at just editing the Czech local outside transfix.

**Comment by PetrDlouhy** [comment]
@nikolai-b Sorry for that, it was easier for me when I was updating our site. I can copy those changes to Transifex if needed.

I am still hoping that we will get some other people involved in translation and editing strings, so Transifex is the way. I will learn, how tu push and pull myself.

**Comment by mvl22** [comment]
Thanks; yes, please do use Transifex for this from now on.

**Comment by nikolai-b** [comment]
Great, I've added a link to 
https://docs.transifex.com/client/installing-the-client
in the translation page, let me know if you have issues.  I'm not sure permissions but I think you should have them.

**Comment by nikolai-b** [comment]
@PetrDlouhy do you still want this PR or should I close it?

**Comment by PetrDlouhy** [comment]
@nikolai-b Please update translation on Transifex (I can't, I am not maintainer) and close this. I will update the translation on Transifex afterwards.

**Comment by nikolai-b** [comment]
@PetrDlouhy Sorry I forgot to update Transifex, I've pushed the changes I've made (and pulled the changes you've made so I'll close this now.  Thanks!

**Comment by mvl22** [comment]
Are we all able to use Transifex from now on?

**Pull request closed without merging**
