### PR TITLE
Use SSL when signed in

### LINKED ISSUE #416: Redirect loop
http://www.cyclescape.org/settings/edit

as linked from
http://www.cyclescape.org/settings/profile

is giving a redirect loop.

### PR DESCRIPTION
**Pull request by nikolai-b**
This should fix #416 but looking at https://github.com/cyclestreets/cyclescape/blob/07a0bb984832ea560248a4771bde3798c4707ad2/app/controllers/application_controller.rb#L43 it seems likely it will break the maps somehow so needs some testing hence https://github.com/cyclestreets/cyclescape/commit/e87145b15f421a279cd1701fb340427e1109a6e4.

### CODE REVIEW

**Comment by nikolai-b** [comment]
This brakes openlayers, put on hold till we have switched to leaflet

**Comment by mvl22** [comment]
Ref #171 - fixing this should be easy and presumably deals with the OpenLayers problem.

**Comment by mvl22** [comment]
Confirmed this is blocked on Leaflet.js completion, hopefully soon.

Switch to side-wide HTTPS on CycleStreets with wildcard subdomains has gone fine so good to replicate this on Cyclescape.

**Comment by nikolai-b** [comment]
@mvl22 I've checked that the maps etc load fine with leaflet and SSL.
You https://github.com/cyclestreets/cyclescape/blob/staging/app/controllers/application_controller.rb#L32 should be able to check your happy on the live site also.  If you are we can merge this!

**Comment by mvl22** [comment]
Seems good to roll out - thanks for getting this all sorted.

I haven't checked though whether e-mails show https:// links.

Each issue page gives a mixed content warning due to http://platform.twitter.com/widgets.js - perhaps this could be fixed up.

Once it's rolled out, do leave the javascript inspector open and have a good wander round the site to ensure there aren't any other cases.

**Comment by nikolai-b** [comment]
Ah yes, I was working on the #151 and must have missed this.  Will update and push live, thanks for checking!

**Comment by nikolai-b** [comment]
I've merged this as the social stuff (with the mixed context fix) has gone live.
I've checked and I _think_ staging will be fine with https but without a cert...
If not I'll put in some fix for staging but as far as I'm concerned the main server should be fine with https only.

**Pull request merged**
