### PR TITLE
Rails4.2

### PR DESCRIPTION
**Pull request by nikolai-b**
This needs a lot more work...

### CODE REVIEW

**Comment by nikolai-b** [comment]
This is hard because the postgis adapter and [rgeo](https://github.com/rgeo/rgeo) are fully overhauled...

**Comment by mvl22** [comment]
> This is hard because the postgis adapter and rgeo are fully overhauled...

Ah, yes I see that rgeo is now a new v3 and this relies on the updated postgis adapter.

Some very brief migration pointers at:
https://github.com/rgeo/activerecord-postgis-adapter/issues/181

**Comment by nikolai-b** [comment]
Merged into staging.  It passes the tests but it is quite a big change so I'd prefer to wait till tomorrow :smile:

**Comment by mvl22** [comment]
Sure; will wait till tomorrow. Well done in getting us to 4.2!

Presumably it will be a small step next to 4.2.4?

**Comment by mvl22** [comment]
Is this ready for master now?

**Pull request merged**
