### PR TITLE
Shaun improvements (for staging)

### PR DESCRIPTION
**Pull request by nikolai-b**
From #345 but rebased against staging.

### CODE REVIEW

**Comment by mvl22** [comment]
@smsm1 I'm still not 100% clear what the effect of this is. Can you clarify what will appear in the e-mails - is it a link to the relevant page on cyclescape/cyklistesobe.cz/whatever, or does it take people directly to the attachment?

Once that is clear hopefully this can be accepted into staging then master ASAP.

**Comment by smsm1** [comment]
There will be 2 links in the email. One will go to relevant page on cyclescape/whatever as per all of the other content types, and the other will take you to the attachment directly.

**Comment by mvl22** [comment]
> One will go to relevant page on cyclescape/whatever as per all of the other content types,
> and the other will take you to the attachment directly.

Sounds great. Thanks!

@gravitystorm, good to go into staging then master if you are happy.

**Comment by nikolai-b** [comment]
Sorry, but this isn't ready.  I don't think that the controller works properly and the spec doesn't have any expectations in it.  I'll have a look at this now.

**Comment by nikolai-b** [comment]
@smsm1 , I've changed the link in the email to go straight to the document url and added a spec.  Are you happy with this?

**Comment by smsm1** [comment]
That looks like a neater solution, than I found. I haven't tested it, however it looks good to me. Thanks for sorting.

**Pull request merged**
