### PR TITLE
First 100 lines translated to es-MX.yml from en-GB.yml

### PR DESCRIPTION
**Pull request by fabianhjr**
This is about 5% done, but it would be great to have it checked by everyone as I go along. I will notify when it is ready.

### CODE REVIEW

**Comment by mvl22** [comment]
Great! Thanks, @fabianhjr.

**Comment by nikolai-b** [comment]
Great work.  Btw, https://github.com/cyclestreets/cyclescape/commit/bac6f70c063952f1e5e142cfed5a78c4a7173140 removes the need to do an translation after line [1025](https://github.com/cyclestreets/cyclescape/pull/397/files#diff-f21ed6fabb43574619fb7d98c92f120dR1025).  Also you might want to look at https://github.com/glebm/i18n-tasks to get rough translation done automatically, hopefully that would mean less typing.

**Comment by dekarl** [comment]
This appears to have gone stale without being merged. Have you considered to [add "Spanish (Mexico)" on Transifex](https://www.transifex.com/cyclescape/cyclescape/languages/) and then upload the file to the "main" resource?
I can [download it for translation](http://docs.transifex.com/translation/translating-offline/) and its in YAML format. According to the documentation you can [simply upload it](http://docs.transifex.com/translation/importing-translations/) and then continue translating on-line, or download the file again for off-line translation.

**Comment by fabianhjr** [comment]
Gone stale. :/

**Comment by gravitystorm** [comment]
Sorry for the delay - I was waiting for the outcome of #547 before working on this, but we're good to go now.

I've created the [es_MX resource on transifex](https://www.transifex.com/cyclescape/cyclescape/language/es_MX/) and added the translations from this pull request to get started. Please feel free to add more translations on Transifex and they will be copied over to this project.

I copied the translations manually. It would have been a bad idea to upload the file in this pull request, since transifex would then mark all of the strings as being translated, making it hard to find which ones were actually in English! There were a few strings that I couldn't match since the source files have changed, and I don't speak Spanish.

Let me know if there's anything else that needs doing.

**Pull request closed without merging**
