### PR TITLE
Release

### PR DESCRIPTION
**Pull request by nikolai-b**
Things that need checking:
- [ ] voting #677 (makes message and issue voting the same)
- [ ] one click unsubscribe from emails #250 
- [ ] adds front page find groups #41

@mvl22 when your happy we can get this live.

### CODE REVIEW

**Comment by mvl22** [comment]
All seems fine to me - some good stuff there!

I'll check the unsubscribe stuff when it goes live as obviously that needs a mail context to check, but sounds like it will be found.

As ever please, do make sure the What's new page is updated.

**Comment by nikolai-b** [comment]
Updated the "What's new page", can we release this @mvl22 ?

**Comment by mvl22** [comment]
Yes, as I said, all seems fine, so please do release - sooner the better.

**Comment by nikolai-b** [comment]
Great, sorry I completely misread your message.  It is deployed and no errors.

**Pull request merged**
