### PR TITLE
613 message hashtags

### PR DESCRIPTION
**Pull request by nikolai-b**

### CODE REVIEW

**Comment by mvl22** [comment]
Is this functionality ready to check for release now on staging?

**Comment by nikolai-b** [comment]
Yes. Please let me know what you think.

**Comment by mvl22** [comment]
The tag links through to an unnecessarily complex URL:

`https://camcycle.cyclescape.org/groups/2-camcycle/hashtags/foobar`

Could this not be:

`https://camcycle.cyclescape.org/hashtags/foobar`

since we already have the group represented by the subdomain?

**Comment by mvl22** [comment]
2. If the message has the same hashtag twice, then the message appears twice in the listing. The messages should be uniqued.

**Comment by mvl22** [comment]
I can forsee that a user requirement is going to be that the hashtag page is going to need a "last viewed entry" memory system like threads do. Let's worry about that later though.

**Comment by mvl22** [comment]
Great; thanks for fixing that. All looks good, so please do make it live :)

**Comment by mvl22** [comment]
All working nicely, thanks Nikolai!

**Pull request closed without merging**
