### PR TITLE
Rails4.1

### PR DESCRIPTION
**Pull request by nikolai-b**
This will upgrade rails to supported version!

### CODE REVIEW

**Comment by mvl22** [comment]
Is this ready for me to test locally now, or do you have further commits planned for 4.1?

**Comment by nikolai-b** [comment]
I good question.  I have been a bit lax with my merging, apologies but I'll try to be clearer from now on.
I suggest the following workflow:

* When I'm working on something it'll be in a branch.
* When I merge into staging then the tests pass and I've done a bit of testing.
* When you've checked it also then we can merge into master.

I'm happy with these commits so test away!

**Comment by mvl22** [comment]
> I suggest the following workflow

Yes, that all sounds sensible and is good to have that defined.

> I'm happy with these commits so test away!

OK, trying now on my local machine.

**Comment by mvl22** [comment]
All seems fine to me after a play around on the site on my dev machine's VM.

Assuming you're happy, and that the tests all pass, I'm happy this goes into master.

**Comment by mvl22** [comment]
I've got time in the coming few days to check over the site for regressions once this is in master.

**Comment by mvl22** [comment]
Thanks - all live now, and seems fine (mail ingesting/sending included, as usual).

**Pull request merged**
