### PR TITLE
New groups

### PR DESCRIPTION
**Pull request by nikolai-b**
Add new group request.  The flow is 
* from the users profile page they can request a new group
* this triggers all site admins to be emailed
* in the admin section new group requests can be :
  * confirmed 
    * this will create a new group with the requester on the committee 
    * email the requester with the group link
  * rejected with a message
    * this email the requester with the rejection message

### CODE REVIEW

**Comment by mvl22** [comment]
Thanks.

I definitely think the request button must not be in the user profile area. It's something that only a very tiny fraction of people would ever need to do, and its presence here implies that it might be something people 'should' be using routinely for some reason. We definitely don't want a preponderance of small groups on particular issues as the system already provides for issue-specific discussion natively.

Instead, can you put it as a standard top-right big green button on the top-right of /groups, which is a page linked from the front page of the www instance: http://www.cyclescape.org/

**Comment by mvl22** [comment]
On the form itself:

- Change label "Name" to "Name of your organisation"

- Change "Shortname" to "Web address", then make the input field about 1/3 of its current length, and put  the main domain name (i.e. ".cyclescape.org"), so that it's clear this a web address

- Change "Website" to "Your organisation's main website"

- Change "E-mail" to "Your organisation's main e-mail address" and remove the hint. Basically I want to avoid people assuming this is an e-mail address that we are going to give them.

- After the second field, add a new field radiobutton:

Default privacy for discussion threads:
(  ) Public - viewable by anyone, whether logged-in or not
(  ) Private - viewable only to members of the group when they are signed in

- Add a second paragraph of introduction: "You will be set as the first Committee member of the group, enabling you to administer it."

**Comment by nikolai-b** [comment]
Done, if your happy let's get this into staging (and master soon)

**Comment by mvl22** [comment]
Still a few adjustments to the form would be good.

1) I'm not keen on the subdomain field labelling. Almost no-one will know what a "subdomain" means. Can you if possible do the change I suggested:

Call the field "Web address", then make the input field about 1/3 of its current length, and put the main domain name (i.e. ".cyclescape.org"), so that it's clear this a web address". I.e.

Web address: [ _____________ ] .cyclescape.org

2) Could you add placeholder = "http:// ..." in the website field

3) Could you make the message field smaller - two lines is quite enough.

4) The default thread privacy field is going to be rather unclear still to people unfamiliar with the site. So, as suggested:

"Default thread privacy"
->
"Default privacy for discussion threads:"

then turn the select field into radiobuttons, with no default set. I've suggested some longer text, so that it is self-explanatory:

( ) Public - viewable by anyone, whether logged-in or not
( ) Private - viewable only to members of the group when they are signed in

**Comment by mvl22** [comment]
Just seen the latest commit. I'm really sorry that I wasn't clear about the first item, as it's still not quite what a I meant - but almost there!

The hint (about being a-z) in the last column should stay, as that is essential information.

What I was meaning is that the second column, that previously just contained the input form, should now contain a shorter input form followed by .cyclescape.org (or rather . + the domain, avoiding hard-coding, since there is an installation in Czech which has a different domain).

i.e. this all goes in the second column:
[ _____________ ] .cyclescape.org

**Comment by nikolai-b** [comment]
@mvl22 sorry I didn't follow first time.  I've added a readonly input field that updates to the web address of the requested group (and readded a reworded hint).
I'll merge down now.

**Comment by mvl22** [comment]
https://github.com/cyclestreets/cyclescape/commit/9f3baf1519f6bd22152685781f5c62aee130e5b2 is still slightly problematic I'm afraid:

1) It has a typo in - cyclescape.org is the correct domain name.

2) cyclescape.org is being hard-coded. At the very least, this should be in the translation file, but ideally it should be dynamically determined from the server environment.

3) Lastly though, can I just check why this seems so complex? Is there some reason that *.<domain> can't just be put in as plain text after the <input> form element? (Excuse my lack of rails/HAML knowledge!) i.e. just ```<input type="text"> .cyclescape.org```

**Comment by nikolai-b** [comment]
Ok,  I've generated the host from the request dynamically in 12db8f0 (it will appear as localhost but it is what we use with here https://github.com/cyclestreets/cyclescape/blob/master/app/controllers/application_controller.rb#L26 )
Regarding 3. I thought it was better to display the new domain, it is simple enough but can remove if you prefer just hard-coded text.

**Comment by nikolai-b** [comment]
Also as we are using a form generator (which wraps each input element with the correct labels and hints) the only place to add `.cyclescape.org` would be the hint, which doesn't seem right.  Hence this is slightly more complicated (but I could easily stop using the form generator for that field, this is more of an explanation of why it might seem a bit over complicated).

**Comment by mvl22** [comment]
Do push into master once you're happy. Thanks for fixing up the dynamic name stuff.

**Pull request merged**
