### PR TITLE
Issue 316 (privacy)

### PR DESCRIPTION
**Pull request by nikolai-b**
This address #316 (superseding and including the commits in #343)

### CODE REVIEW

**Comment by nikolai-b** [comment]
Also including and superseding #352

**Comment by nikolai-b** [comment]
@mvl22 I have addressed the points in https://github.com/cyclestreets/cyclescape/issues/316#issuecomment-101617332
I am very pleased you asked about the 404 as the other method didn't seem to make sense but from [this commit](https://github.com/cyclestreets/cyclescape/commit/2e03a1eedea0c697075e99f6f15cfef9cd395813) I thought it was what you wanted.

**Comment by nikolai-b** [comment]
@mvl22 Regarding https://github.com/cyclestreets/cyclescape/issues/316#issuecomment-105304659 I cannot re-create this.  I assume you've run all the migrations?  I'm testing this by pulling in the prod database and running the migrations on that (and it all works).

Could this be something to do with your local db, can you try using the prod data?

```
Started PUT "/users/1212-nikolai-b/profile" for 127.0.0.1 at 2015-06-01 21:47:52 +0100
Processing by User::ProfilesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "user_profile"=>{"retained_picture"=>"", "remove_picture"=>"0", "website"=>"", "about"=>"- Some text", "visibility"=>"public"}, "commit"=>"Save", "user_id"=>"1212-nikolai-b"}
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1212 AND ("users".deleted_at IS NULL) LIMIT 1
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 AND ("users".deleted_at IS NULL) LIMIT 1  [["id", "1212-nikolai-b"]]
  UserProfile Load (0.6ms)  SELECT "user_profiles".* FROM "user_profiles" WHERE "user_profiles"."user_id" = 1212 LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Redirected to http://localhost:3000/users/1212-nikolai-b/profile
```

**Comment by nikolai-b** [comment]
@mvl22 actually this is in staging now so could you check that you are still getting the error when testing against that?  Thanks!

**Comment by mvl22** [comment]
Yes, I meant to say that this is indeed working now.

**Comment by nikolai-b** [comment]
Great. There are a few other changes in staging so when your ready this can go live.
I presume that would mean an email going out and so maybe I should cherry-pick the new settings routes to master now?

**Comment by mvl22** [comment]
If that's easy enough, that would be best, yes. I need to sort out the privacy policy then the e-mail first, yes.

**Comment by mvl22** [comment]
There naturally needs to be complete clarity to users about how the full (real) name and display name are used.

In the two texts:
https://github.com/cyclestreets/cyclescape/blob/issue-316/config/locales/forms.en-GB.yml#L70-L71
at present it is not clear what happens in the scenario where a user does not have a display name set but it is being viewed by people not in their groups.

Could you adjust the hint(s) for those two fields to make this match the behaviour, as checked by the test specs?

Privacy policy is now written but there needs to be clarity on the above first so it can be finalised fully.

**Comment by mvl22** [comment]
NB This code covers almost all the points in https://github.com/cyclestreets/cyclescape/issues/218

**Comment by nikolai-b** [comment]
Does 66e9cd4 adequately this cover what happens if your display name is not set?
Code is https://github.com/cyclestreets/cyclescape/blob/staging/app/models/user.rb#L229

Also I've made #376 which adds the profile link stuff (to make the email text simpler).

**Comment by mvl22** [comment]
@nikolai-b Yes, it does I think - thanks.

**Comment by nikolai-b** [comment]
Phew, so the privacy policy is in master 1550bc8926f1af72, it was slightly more involved than just adding an html file.  Looking forward to this going live.

**Comment by mvl22** [comment]
Can the URL just be /privacypolicy rather than be prefixed with /pages ?

Also, should this string be quoted?
https://github.com/cyclestreets/cyclescape/commit/1550bc8926f1af72e35e5ef5a34807700f42d740#diff-63ce76535a96f7acb5e8e66cea31936bR566

**Comment by nikolai-b** [comment]
argg, sorry about that.  Hadn't saved the file.  I've re-pushed and all works fine now.  

> Can the URL just be /privacypolicy rather than be prefixed with /pages ?

I'd really prefer not as it fits in the the "What's new page" and is served via our pages controller (https://github.com/cyclestreets/cyclescape/blob/master/app/controllers/pages_controller.rb).  How important is it?

**Comment by mvl22** [comment]
> I'd really prefer not as it fits in the the "What's new page"

Fair enough. Rolled out now - thanks.

**Comment by nikolai-b** [comment]
One other thing, is this line meant to be in the policy? https://github.com/cyclestreets/cyclescape/commit/1550bc8926f1af72e35e5ef5a34807700f42d740#diff-396621c3cbcd46d3e09a8bfe236c956aR65

**Comment by mvl22** [comment]
OK, the rest of the privacy changes can now be merged into master.

**Pull request merged**
