### PR TITLE
Performance

### LINKED ISSUE #844: My Cyclescape page is very slow to load
About 5 seconds to load.

Could we do some profiling again to see which component(s) are being slow?

(Perhaps do this after the Rails 5 upgrade as that will presumably change things or might have optimisations.)

### PR DESCRIPTION
**Pull request by nikolai-b**
Fixes #844 and generally increases site performance.  Given the increased caching there is a small possibility we might see a strangeness with thread content being stale.  There is an issue with the CI that is finding a JS error but I can't recreate locally.

### CODE REVIEW

**Comment by mvl22** [comment]
These look like a nice set of performance improvements. Let me know when this is ready to test (and do flag up anything particularly of note), so we can get these live sooner rather than later.

**Comment by nikolai-b** [comment]
@mvl22 this should be on staging soon.  I've started caching views so they are rendered once but content is shown differently depending on what role a person has (e.g. an admin can censor whereas a normal user cannot).  Also to cache I've extracted the time ago code from Ruby to JavaScript so we don't get the same bug as #849 .  I'm also getting all of a users thread subscriptions in one SQL call instead of per thread so that is another area that there could be bugs.

Testing I've logged in as different users (with different roles) and checked to see that the pages make sense.  If we get an issue with caching it is very easy to revert it so if you've not got time to test then I'll deploy this soon and we can revert if there are problems.

I spent a while monitoring the performance improvements and on my local machine they were hard to pin down as rails reloads code in a development environment when a change is made but it was faster.

**Comment by mvl22** [comment]
There is a regression - the dates are not showing as "About 9 hours ago" etc. Looks like timeago isn't being compiled in.

Screen Shot 2019-07-10 at 09 27 49

**Comment by mvl22** [comment]
Other than that regression, this all looks good. So please do just fix that up and deploy live.

**Pull request merged**
