### PR TITLE
Allow a user to edit an issue after 24 hours

### LINKED ISSUE #506: Allow editing of some Issue fields by the issue creator
An LCC user has asked:
> Is there a way that in Cyclescape I can edit consultation deadlines that have changed, either in a discussion thread or in an issue? This seems quite a common scenario, yet I can't figure out how to deal with it.
> Kind regards,
> Dominic

He is quite right, this need has occurred several times and I have had to intervene as a sysadmin to change the deadline date. Note that the Issue Map uses the Issue deadline to determine the appearance of an issue.

Editing the Deadline is a minimum requirement. I think the Description, External link and photo should also be editable by the issue creator as new facts may well emerge during the Issue's currency.

### PR DESCRIPTION
**Pull request by nikolai-b**
Closes #506

### CODE REVIEW

**Comment by georgio8** [comment]
LCC users are asking about this again. I don't believe it has been implemented yet.

**Comment by nikolai-b** [comment]
Thanks @georgio8 .  You are able to edit an issue that you created without any time limits.  If a user has difficulties would you mind letting me know the specific user and issue?

I've just checked by logging in as a non-admin user and I can see the cog:
3c49e165-b8f0-4c0e-90c7-430d11ef9667

**Comment by georgio8** [comment]
Thanks Nikolai, you’re right of course, our info was clearly very stale. 

The user concerned (Simon Munk) is pleased, but now wants to be able to edit some Thread properties for threads he creates.

Cheers,

George

**Comment by georgio8** [comment]
I guess your aware that the problem still persists but I thought it might be helpful if I sent a sample, together with the raw text.

> Begin forwarded message:
> 
> From: Aldo <notifications@cyclescape.org>
> Subject: [Cyclescape] "Mill Road (transporation) Survey (for edit)" (Cambridge Cycling Campaign)
> Date: 8 February 2019 at 14:15:35 GMT
> To: George Coulouris <george@coulouris.net>
> Reply-To: message-134bff026e316e6e8256@cyclescape.org
> 
> A new discussion titled Mill Road (transporation) Survey (for edit) <http://www.cyclescape.org/threads/4561> has been created on issue Mill Road (transporation) Survey (for edit) <http://www.cyclescape.org/issues/3648-mill-road-transporation-survey-for-edit> for the Cambridge Cycling Campaign <http://www.cyclescape.org/groups/2-camcycle> group.
> 
> Aldo <http://www.cyclescape.org/users/2893-aldo/profile> wrote:
> 
> <p>In the coming weeks we, UoC Students from the Cambridge Hub, are going to do a survey on Mill Road in order to find out how people get to Mill Road and how they interact with it. The survey will be compared with the survey done last November in order to build momentum for the car-free Mill Road project.</p> <p>We would love your input. Please give suggestions below.</p> <p>For the survey, click on the link below.</p> <p>Deadline for edits is this friday.</p>
> 
> You aren't subscribed to this discussion thread, so you won't receive any more updates but you can change that on the discussion thread page <http://www.cyclescape.org/threads/4561>. 
> You have received this message because your preferences indicate that you would like us to notify you on matters in your group. 
> To stop these notifications, edit your user preferences <http://www.cyclescape.org/users/49-george-coulouris/prefs/edit>.


Raw text:

 Content preview:  A new discussion titled "Mill Road (transporation) Survey
   (for edit)" has been created on issue "Mill Road (transporation) Survey (for
    edit)" for the Cambridge Cycling Campaign group. Aldo wrote: In t
 
 Content analysis details:   (-0.2 points, 4.0 required)
 
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -0.5 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]
  0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was blocked.
                             See
                             http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                              for more information.
                             [URIs: cyclescape.org]
 -0.5 RCVD_IN_MSPIKE_H2      RBL: Average reputation (+2)
                             [31.204.155.103 listed in wl.mailspike.net]
  0.7 SPF_SOFTFAIL           SPF: sender does not match SPF record (softfail)
  0.0 HTML_MESSAGE           BODY: HTML included in message
  0.2 AWL                    AWL: Adjusted score from AWL reputation of From: address
X-Spam-Flag: NO


----==_mimepart_5c5d8f075eebc_44813a10b02832
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

A new discussion titled "Mill Road (transporation) Survey (for edit)" has been created on
issue "Mill Road (transporation) Survey (for edit)" for the Cambridge Cycling Campaign group.

Aldo wrote:
In the coming weeks we, UoC Students from the Cambridge Hub, are going to do a survey on Mill Road in order to find out how people get to Mill Road and how they interact with it. The survey will be compared with the survey done last November in order to build momentum for the car-free Mill Road project.

We would love your input. Please give suggestions below.

For the survey, click on the link below.

Deadline for edits is this friday.

You aren't subscribed to this discussion thread, so you won't receive any
more updates. You can read the whole thread, and subscribe to it at:
http://www.cyclescape.org/threads/4561

--------
You have received this message because your preferences indicate that you
would like us to notify you on matters in your group.

To stop these notifications, edit your user preferences at:
http://www.cyclescape.org/users/49-george-coulouris/prefs/edit


----==_mimepart_5c5d8f075eebc_44813a10b02832
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
</head>
<body>
<p>
A new discussion titled
<a href="http://www.cyclescape.org/threads/4561">Mill Road (transporation) Survey (for edit)</a>
has been created on issue
<a href="http://www.cyclescape.org/issues/3648-mill-road-transporation-survey-for-edit">Mill Road (transporation) Survey (for edit)</a>
for the
<a href="http://www.cyclescape.org/groups/2-camcycle">Cambridge Cycling Campaign</a>
group.
</p>
<p>
<span class='name'>
<a href="http://www.cyclescape.org/users/2893-aldo/profile">Aldo</a>
</span>

wrote:
</p>
<p style='margin-left:20px'>&lt;p&gt;In the coming weeks we, UoC Students from the Cambridge Hub, are going to do a survey on Mill Road in order to find out how people get to Mill Road and how they interact with it. The survey will be compared with the survey done last November in order to build momentum for the car-free Mill Road project.&lt;/p&gt;
&lt;p&gt;We would love your input. Please give suggestions below.&lt;/p&gt;
&lt;p&gt;For the survey, click on the link below.&lt;/p&gt;
&lt;p&gt;Deadline for edits is this friday.&lt;/p&gt;</p>

<hr style='border:1px solid #E6E6E6;'>
<div style='font-size:12px;color:rgb(153, 153, 153)'>
You aren't subscribed to this discussion thread, so you won't receive any
more updates but you can change that on the
<a href="http://www.cyclescape.org/threads/4561">discussion thread page</a>.
<br>
You have received this message because your preferences indicate that you
would like us to notify you on matters in your group.
<br>
To stop these notifications, edit
<a href="http://www.cyclescape.org/users/49-george-coulouris/prefs/edit">your user preferences</a>.
</div>

</body>
</html>

----==_mimepart_5c5d8f075eebc_44813a10b02832--

**Comment by mvl22** [comment]
> I guess you're aware that the problem still persists but I thought it might be helpful if I sent a sample, together with the raw text.

I can't see what in that e-mail refers to editing of an issue after 24 hours. Was that about something else, e.g. HTML problems, as in issue #834? If so, could you reproduce your posting there?

**Comment by mvl22** [comment]
> The user concerned (Simon Munk) is pleased, but now wants to be able to edit some Thread properties for threads he creates.

I've created new issue #836 on this separate matter.

**Pull request merged**
