### PR TITLE
Add Poll Message type

### LINKED ISSUE #612: Add a poll feature
It would be good to have some kind of poll or vote feature in individual threads to assist with decision making. Ideally at least 4 options.

### PR DESCRIPTION
**Pull request by nikolai-b**
Closes #612

### CODE REVIEW

**Comment by mvl22** [comment]
Presumably this is ready for testing on staging?

**Comment by mvl22** [comment]
The layout for the poll link is a bit screwed - could you tighten this up, by moving Link onto the previous line, to make space for Poll at the start of the second row?

Screen Shot 2019-12-20 at 12 03 59

**Comment by mvl22** [comment]
The minus button alignment looks wrong too:

Screen Shot 2019-12-20 at 12 11 24

**Comment by nikolai-b** [comment]
Thanks.  I didn't spend any time on the layout as you might have had larger changes to the structure.  I've moved them now:

Screenshot from 2019-12-20 21-34-32

**Comment by mvl22** [comment]
Looks good to go, thanks.

**Pull request merged**
