### PR TITLE
Remove ability to see users profiles and full names unless permitted

### PR DESCRIPTION
**Pull request by nikolai-b**
As per https://github.com/cyclestreets/cyclescape/pull/343#issuecomment-76964155 making this PR against staging instead of master

### CODE REVIEW

**Comment by nikolai-b** [comment]
@mvl22 regarding https://github.com/nikolai-b/cyclescape/commit/cc819a0b267b77f51f9f9570486281d991bab74a this is a privacy change, can you confirm this is what your after?

**Comment by mvl22** [comment]
> @mvl22 regarding nikolai-b@cc819a0 this is a privacy change, can you confirm this is what your after?

@nikolai-b Can you describe what specifically the change in behaviour is here, so I can check this. (NB I'm trying to get an installation running on my mac but rammed with other work at the moment, so anything to help me be clear would be much appreciated!)

**Comment by nikolai-b** [comment]
Sure but I'm hard pressed to explain it better than 'show full name on profile for users in same group'.  If you share a group with a user then you can always see their full name on the profile page.

**Comment by mvl22** [comment]
Sounds like a good part of the work in that wider privacy issue - thanks. Will have a look over in practice, though if @gravitystorm is happy, do merge in to staging then master.

**Comment by nikolai-b** [comment]
@mvl22 I told you this was is staging but it isn't!
Before this:
* your full name was hidden if you had set a display name (apart for when a user attempted to join a group, and then to the admins only)
* your profile was always visible to everyone

After this:
* users now can see the full name (in the profile) of anyone in an intersecting group, [see here](https://github.com/cyclestreets/cyclescape/pull/352/files#diff-f77911943f02fefecdd7f663653d5796R106).
* if users have profile_visibility set to private (in the user preferences) then their profile will not be visible publicly (only if they are in intersecting groups)

**Comment by nikolai-b** [comment]
@mvl22 this is also in https://github.com/cyclestreets/cyclescape/tree/issue-316 (i.e. branch issue-316) if you want to test locally.

**Pull request closed without merging**
